[package]
name = "bws_plugin_template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
async-net = "1.6"
futures-lite = "*"
async-ffi = "0.3"
bws_plugin = { path = "../bws_plugin" }