[package]
name = "bws_plugin_template"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bws_plugin_interface = { path = "../bws_plugin_interface" }
abi_stable = "0.10"